<?php defined('PREVENT_DIRECT_ACCESS') OR exit('No direct script access allowed'); ?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Login | ProductHub</title>
<style>
:root{--purple:#635bff;--purple2:#7c3aed;--ink:#17172d;--muted:#7c8498}*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:Inter,Segoe UI,Arial,sans-serif;background:radial-gradient(circle at 20% 10%,#4338ca55,transparent 35%),radial-gradient(circle at 90% 90%,#7c3aed55,transparent 32%),#111126;color:#fff;display:grid;place-items:center;padding:24px}.login-wrap{width:min(930px,100%);display:grid;grid-template-columns:1.05fr .95fr;background:#fff;border-radius:25px;overflow:hidden;box-shadow:0 30px 90px #0007}.hero{padding:55px;background:linear-gradient(145deg,#20204a,#14142b);position:relative;overflow:hidden}.hero:after{content:'';position:absolute;width:220px;height:220px;border-radius:50%;background:#7c3aed33;right:-80px;bottom:-80px}.logo{width:52px;height:52px;border-radius:16px;background:linear-gradient(135deg,#8b5cf6,#5b5cf6);display:grid;place-items:center;font-weight:900;margin-bottom:55px}.hero h1{font-size:38px;line-height:1.08;margin:0 0 16px;letter-spacing:-1px}.hero p{color:#b7b9cc;line-height:1.7;font-size:14px;max-width:390px}.feature{display:flex;gap:12px;margin-top:38px;color:#dfe0eb;font-size:13px}.check{width:25px;height:25px;border-radius:8px;background:#635bff33;color:#a9a2ff;display:grid;place-items:center}.form-side{padding:55px;color:var(--ink);display:flex;flex-direction:column;justify-content:center}.form-side h2{font-size:28px;margin:0 0 8px}.welcome{color:var(--muted);font-size:13px;margin:0 0 28px}.field{margin:17px 0}.field label{display:block;font-size:12px;font-weight:800;margin-bottom:8px}.input-wrap{position:relative}.input-wrap span{position:absolute;left:13px;top:12px;color:#a0a7b8}.field input{width:100%;padding:13px 14px 13px 39px;border:1px solid #e1e5ee;border-radius:11px;outline:0;font-size:14px;background:#fbfcff}.field input:focus{border-color:#918aff;box-shadow:0 0 0 4px #635bff12}.btn{width:100%;border:0;padding:14px;border-radius:11px;background:linear-gradient(135deg,var(--purple),var(--purple2));color:#fff;font-weight:800;font-size:14px;cursor:pointer;box-shadow:0 10px 25px #635bff2b}.error{padding:12px;border-radius:10px;background:#fff0f2;color:#c53055;font-size:12px;font-weight:700;margin-bottom:14px}.hint{margin-top:22px;text-align:center;color:#a0a7b8;font-size:11px}
@media(max-width:700px){.login-wrap{grid-template-columns:1fr}.hero{display:none}.form-side{padding:38px 28px}}
</style>
</head>
<body>
<div class="login-wrap">
<section class="hero"><div class="logo">PM</div><h1>Welcome to<br>ProductHub.</h1><p>A clean and secure inventory workspace built for your LavaLust CRUD laboratory exercise.</p><div class="feature"><div class="check">✓</div><div>Authenticated access and protected product management</div></div><div class="feature"><div class="check">✓</div><div>Create, update, view, and delete products</div></div></section>
<section class="form-side"><h2>Sign in</h2><p class="welcome">Enter your account to continue to the dashboard.</p><?php if (!empty($error)): ?><div class="error">⚠ <?= htmlspecialchars($error) ?></div><?php endif; ?><form action="<?= site_url('/login/authenticate') ?>" method="post"><div class="field"><label>USERNAME</label><div class="input-wrap"><span>◎</span><input type="text" name="username" required autocomplete="username" placeholder="Enter username"></div></div><div class="field"><label>PASSWORD</label><div class="input-wrap"><span>●</span><input type="password" name="password" required autocomplete="current-password" placeholder="Enter password"></div></div><button class="btn" type="submit">Sign In →</button></form><div class="hint">LavaLust • Laboratory Exercise No. 5</div></section>
</div>
</body>
</html>
